package com.example.nflsimtext.ui

import android.content.ActivityNotFoundException
import android.content.Context
import android.content.Intent
import android.content.pm.PackageManager
import android.net.Uri
import android.os.Build
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import com.example.nflsimtext.ui.components.SecondaryButton
import com.example.nflsimtext.ui.components.SituationBlock
import com.example.nflsimtext.ui.theme.NdTheme

/** Where the policy lives and who answers: the same as the store listing's (docs/play-store/RELEASE.md). */
object About {
    const val PRIVACY_URL = "https://itstrue54.github.io/gridiron-dynasty/"
    const val SUPPORT_EMAIL = "amfootballsimtext@gmail.com"

    /** The privacy policy in short, as the app can say it without a connection. */
    val PRIVACY = listOf(
        "No accounts, no internet access, no analytics, no ads.",
        "Your saves stay on your phone. If you have turned on your phone's own backup, Android may copy them to your Google account.",
        "Files you import, export or share go only where you choose.",
    )

    /** "1.0 (1)": what the player tells support. */
    fun version(context: Context): String = runCatching {
        val info = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU)
            context.packageManager.getPackageInfo(context.packageName, PackageManager.PackageInfoFlags.of(0))
        else @Suppress("DEPRECATION") context.packageManager.getPackageInfo(context.packageName, 0)
        val code = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) info.longVersionCode
            else @Suppress("DEPRECATION") info.versionCode.toLong()
        "${info.versionName} ($code)"
    }.getOrDefault("unknown")

    /** The subject line an email to support starts with, so the version comes along. */
    fun subject(version: String) = "Gridiron Dynasty $version"
}

/**
 * About the app (behind Settings): the version, the privacy policy in short,
 * where to read the rest, and who to write to. The app has no internet
 * access of its own: the policy opens in the phone's browser and the email
 * in its mail app.
 */
@Composable
fun AboutScreen(onBack: () -> Unit) {
    val c = NdTheme.colors
    val context = LocalContext.current
    val version = remember { About.version(context) }
    var note by remember { mutableStateOf<String?>(null) }
    fun open(intent: Intent, missing: String) {
        try { context.startActivity(intent) } catch (_: ActivityNotFoundException) { note = missing }
    }
    val wide = Modifier.fillMaxWidth().padding(top = NdTheme.spacing.s)

    ScreenList {
        item {
            Column {
                Text("About", style = NdTheme.type.display, color = c.chalk)
                Text("Gridiron Dynasty, version $version.", style = NdTheme.type.body, color = c.chalkDim)
                Text("The clubs and players are fictional and generated by the app.",
                    style = NdTheme.type.caption, color = c.chalkDim, modifier = Modifier.padding(top = NdTheme.spacing.xs))
            }
        }
        item {
            SituationBlock("Privacy") {
                About.PRIVACY.forEach {
                    Text("· $it", style = NdTheme.type.body, color = c.chalk, modifier = Modifier.padding(bottom = NdTheme.spacing.xs))
                }
                SecondaryButton("Read the full privacy policy", {
                    open(Intent(Intent.ACTION_VIEW, Uri.parse(About.PRIVACY_URL)),
                        "No browser to open it in. It is at ${About.PRIVACY_URL}")
                }, wide)
            }
        }
        item {
            SituationBlock("Support") {
                Text("Questions, bugs, ideas: ${About.SUPPORT_EMAIL}", style = NdTheme.type.body, color = c.chalk)
                SecondaryButton("Email support", {
                    open(Intent(Intent.ACTION_SENDTO, Uri.parse("mailto:")).apply {
                        putExtra(Intent.EXTRA_EMAIL, arrayOf(About.SUPPORT_EMAIL))
                        putExtra(Intent.EXTRA_SUBJECT, About.subject(version))
                    }, "No mail app to write it in. The address is ${About.SUPPORT_EMAIL}")
                }, wide)
            }
        }
        note?.let { item { Text(it, style = NdTheme.type.caption, color = c.chalkDim) } }
        item { SecondaryButton("Back", onBack, Modifier.fillMaxWidth()) }
    }
}
